// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpI0DyjQifPJI9OaozmBhlNOLh4amkiEU',
    appId: '1:377345894977:web:ef26601be4ae2a7425f4c0',
    messagingSenderId: '377345894977',
    projectId: 'firechat-dc870',
    authDomain: 'firechat-dc870.firebaseapp.com',
    databaseURL: 'https://firechat-dc870-default-rtdb.firebaseio.com',
    storageBucket: 'firechat-dc870.appspot.com',
    measurementId: 'G-6ELTJNDDBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXXEJjdxY5mo_Xaumzve3EZJaUOUo62-k',
    appId: '1:377345894977:android:73a12cf327471fbc25f4c0',
    messagingSenderId: '377345894977',
    projectId: 'firechat-dc870',
    databaseURL: 'https://firechat-dc870-default-rtdb.firebaseio.com',
    storageBucket: 'firechat-dc870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm--LpHt-eQkLauwHHUjWP8nZmOUDrhIA',
    appId: '1:377345894977:ios:a3f68ec4f334600825f4c0',
    messagingSenderId: '377345894977',
    projectId: 'firechat-dc870',
    databaseURL: 'https://firechat-dc870-default-rtdb.firebaseio.com',
    storageBucket: 'firechat-dc870.appspot.com',
    iosClientId: '377345894977-dekj93057qfunmet3s75j9pqudh1nqrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm--LpHt-eQkLauwHHUjWP8nZmOUDrhIA',
    appId: '1:377345894977:ios:a3f68ec4f334600825f4c0',
    messagingSenderId: '377345894977',
    projectId: 'firechat-dc870',
    databaseURL: 'https://firechat-dc870-default-rtdb.firebaseio.com',
    storageBucket: 'firechat-dc870.appspot.com',
    iosClientId: '377345894977-dekj93057qfunmet3s75j9pqudh1nqrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireChat',
  );
}
